# Generated by Django 5.2.17 on 2026-08-26 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('accessed_count', models.PositiveIntegerField(default=1)),
                ('request_method', models.CharField(choices=[('POST', 'Post'), ('PUT', 'Put'), ('PATCH', 'Patch')], max_length=16)),
                ('request_body', models.TextField()),
                ('request_path', models.CharField(max_length=255)),
                ('request_digest', models.BinaryField(max_length=32)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_content_type', models.CharField(blank=True, max_length=255)),
                ('response_saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='drf_idempot_created_c72a64_idx'), models.Index(fields=['modified_at'], name='drf_idempot_modifie_409e58_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'user'), name='unique_key_user')],
            },
        ),
    ]
