# Generated by Django 5.2.17 on 2026-10-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_idempotencykey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencykey',
            name='response_cookies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='idempotencykey',
            name='response_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
